canonical/documentation-builder

README.rst, ubuntudesign/documentation_builder/cli.py
- Make `./html` the default output destination
- Allow `documentation-builder` without any options to build the current directory again
Fixes #2
=> Default build directory: ./build

README.rst, ubuntudesign/documentation_builder/build.py, ubuntudesign/documentation_builder/cli.py
A new option for ignoring markdown files. Defaults to ignoring README.md.
=> --ignore-file option

ubuntudesign/documentation_builder/__init__.py
So that people can query which version of the module is installed:
``` bash
from ubuntudesign import documentation_builder
assert documentation_builder.__version__.split('.') > ['0', '3', '0']
```
=> Add __version__ property

requirements.txt, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/resources/wrapper.jinja2
Fixed #19.
QA
--
To test it, add `table_of_contents: true` to the metadata at the top of the `en/index.md` file in maas-docs, and build it. You should see a table of contents on the right.
=> Sticky table of contents

.gitignore, README.rst, bin/documentation-builder, bin/wrapper.sh, requirements.txt, setup.py, snapcraft.yaml, structure/en/index.md, structure/fr/index.md, structure/metadata.yaml
Setup files properly to support building from snap:
- Build snap from local directory
- Remove pip install instructions for binary
- Don't mention the binary in setup.py
QA
--
Check you can build the snap:
``` bash
snapcraft clean
snapcraft
sudo snap install --force-dangerous documentation-builder_0.4.5_amd64.snap
```
Now test out `documentation-builder`.
Check you can also install from store:
``` bash
sudo snap remove documentation-builder
sudo snap install documentation-builder
```
Test out `documentation-builder` again.
=> Make snap install official

README.rst, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/cli.py
Any files where the built file both exists and is newer than the source markdown file will be skipped.
This will help address #20, as subsequent builds should now take under a second.
I've also removed the `--ignore-files` option and added `--quiet`.
QA
---
Try it out:
``` bash
documentation-builder  # run this twice. Then try touching a markdown file and running it again.
documentation-builder --quiet  # Try this too
```
=> Ignore unmodified files

README.rst, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/cli.py, ubuntudesign/documentation_builder/resources/wrapper.jinja2
If you supply the `--build-version-branches` flag, instead of looking for markdown files directly in the base directory,
it will look for a `versions` file of branches, check out each mentioned branch, and then build each of those branches into
a subdirectory in the build directory.
Fixes #5 and #11.
QA
--
Inside a repository with multiple branched, e.g.:
``` bash
$ git branch
master
1.0
1.1
```
Make sure there's a `versions` file mentioning those branches:
``` bash
$ cat versions
1.0
1.1
```
Now try it out:
``` bash
$ pip3 install {path-to-documentation-builder}
$ {path-to-documentation-builder}/bin/documentation-builder --build-version-branches
$ tree build
build
├── 1.0
│   └── en
│       └── index.html
└── 1.1
└── en
└── index.html
```
=> New option: --build-version-branches

docs/en/index.md, setup.py, snapcraft.yaml, tests/test_builder.py, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/cli.py, ubuntudesign/documentation_builder/operations.py, ubuntudesign/documentation_builder/resources/template.html
An option to put google-tag-manager code in the built HTML files.
Including all tests.
Fixes #34.
QA
--
Try building documentation with `--tag-manager-code=GTM_xxxxxx` and see the tag manager code in the built HTML files.
=> Implement tag-manager-code option

CHANGES.txt, setup.cfg, setup.py, snapcraft.yaml, tests/fixtures/builder/output_search/en/index.html, tests/fixtures/builder/output_search/en/subfolder/nested.html, tests/fixtures/builder/output_search/fr/index.html, tests/test_builder.py, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/cli.py, ubuntudesign/documentation_builder/resources/template.html
Add the new options `--search-url`, `--search-placeholder`, `--search-domain`.
These will enable a search input field in the header of each page.
This is to support search on docs.ubuntu.com.
QA
--
``` bash
git clone https://github.com/canonicalltd/maas-docs
cd maas-docs
python3 -m venv env
git clone -b search https://github.com/nottrobin/documentation-builder
env/bin/pip install ./documentation-builder
env/bin/python3 ./documentation-builder/bin/documentation-builder --force --search-url "https://docs.ubuntu.com/search" --search-placeholder "Search MAAS docs" --search-domain "docs.ubuntu.com/maas"
```
This should build the docs with the new search form. Now open `build/en/index.html` in your browser, see there's a search box in the top right. Using it should lead you to …
=> Add optional search form

CHANGES.txt, setup.py, snapcraft.yaml, tests/fixtures/builder/output_basic/en/index.html, tests/fixtures/builder/output_basic/en/subfolder/nested.html, tests/fixtures/builder/output_basic/fr/index.html, tests/fixtures/builder/output_media_path/en/index.html, tests/fixtures/builder/output_media_path/en/subfolder/nested.html, tests/fixtures/builder/output_media_path/fr/index.html, tests/fixtures/builder/output_media_url/en/index.html, tests/fixtures/builder/output_media_url/en/subfolder/nested.html, tests/fixtures/builder/output_media_url/fr/index.html, tests/fixtures/builder/output_no_media/en/index.html, tests/fixtures/builder/output_no_media/en/subfolder/nested.html, tests/fixtures/builder/output_no_media/fr/index.html, tests/fixtures/builder/output_search/en/index.html, tests/fixtures/builder/output_search/en/subfolder/nested.html, tests/fixtures/builder/output_search/fr/index.html, tests/fixtures/builder/output_versions/1.0/en/index.html, tests/fixtures/builder/output_versions/1.0/en/subfolder/nested.html, tests/fixtures/builder/output_versions/1.0/fr/index.html, tests/fixtures/builder/output_versions/latest/en/index.html, tests/fixtures/builder/output_versions/latest/en/subfolder/nested.html, tests/fixtures/builder/output_versions/latest/fr/index.html, ubuntudesign/documentation_builder/resources/template.html
Fixes #58 by adding the title from the Markdown metadata to the meta title markup element.
QA
--
Build a set of documentation with this new version:
``` bash
git clone https://github.com/canonicalltd/ubuntu-core-docs
cd ubuntu-core-docs
python3 -m venv env
git clone -b 58-meta-title https://github.com/nottrobin/documentation-builder
env/bin/pip install ./documentation-builder
env/bin/python3 ./documentation-builder/bin/documentation-builder
```
Now open up `build/en/index.html`, or any other page, and see that the `<title>` value is now of the format `[page_title] | [site title]`.
=> Use the defined page meta title

.gitignore, README.rst
Also ignore the `env3/` directory that these instructions suggest you
generate.
QA
---
Try following the [development instructions](https://github.com/nottrobin/documentation-builder/tree/development-instructions#Development).
=> Add development instructions to the README.rst

setup.py, snapcraft.yaml, ubuntudesign/documentation_builder/resources/template.html
Added some styling for search at small screen
```
python3 -m venv env3 && source env3/bin/activate  # Create encapsulated environment
pip install -e .  # Install the module in editable mode
bin/documentation-builder --source-folder docs --search-url /search --force
xdg-open build/en/index.html  # Open up the documentation page
```
Check the page in all viewports
[Design](https://www.dropbox.com/work/00_web_team/Docs%20theme/Website/Deliverables/Search?preview=Mobile+Portrait.jpg)
=> Search small screen

CHANGES.txt, setup.py, snapcraft.yaml, ubuntudesign/documentation_builder/resources/template.html
QA
--
``` bash
git clone https://github.com/canonicalltd/docs-landscape
cd docs-landscape
git clone -b fix-navigation-wrapping https://github.com/nottrobin/documentation-builder
python3 -m venv env3
env3/bin/pip install ./documentation-builder
env3/bin/python ./documentation-builder/bin/documentation-builder
```
Now open `build/en/index.html` and check the "Landscape On-Premises" navigation item wraps more sensibly.
=> Fix nav wrapping

ubuntudesign/documentation_builder/resources/template.html
Used to be broken, like this:
Now it looks like this:
QA
--
``` bash
python3 -m venv env3
source env3/bin/activate
pip install -e .
cd ..
cd maas-docs  # Or clone it if you don't have it
../documentation-builder/bin/documentation-builder --force
```
Now open `build/en/index.html` and check the third-level nav chevrons look fixed.
=> Fix the expand/collapse chevrons on 3rd level nav

ubuntudesign/documentation_builder/builder.py
Because it breaks links in markup.
See #77.
=> Disable URLize

.gitignore, README.rst, docs/en/metadata.yaml, ubuntudesign/documentation_builder/resources/template.html
Developed the ability to add an external attribute to a navigation menu. Drive by fix in the Readme.
- Pull this branch
- Do the following:
``` bash
python3 -m venv env3 && source env3/bin/activate  # Create encapsulated environment
pip install -e .  # Install the module in editable mode
documentation-builder --source-folder docs  # build the documentation-builder's own documentation
xdg-open build/en/index.html  # Open up the documentation page
```
- Check that the menu item "Project repository" has an external class on it. 
- Check the others don't
- I will update the styling in a follow-up branch
=> Add external link functionality to navigation

ubuntudesign/documentation_builder/resources/template.html
Hide the table of contents on tablet and small screens to allow more room for body copy. This will change when UX have planned what to do on small screens.
Fixes https://github.com/vanilla-framework/vanilla-docs-theme/issues/34
=> Hide the table of contents on tablet and small screens

README.rst, tests/fixtures/parse_markdown/plain_markdown.html, tests/test_operations.py, ubuntudesign/documentation_builder/operations.py
Make the table of contents opt out. Update some failing tests.
- Pull this branch
- `python3 -m venv env3 && source env3/bin/activate`
- `pip install -e .`
- `rm -rf build && documentation-builder --source-folder docs`
- `xdg-open build/en/index.html`
- Check the index has a TOC
- Go to How to structure documentation page
- See there is a TOC too
Fixes https://github.com/canonical-webteam/documentation-builder/issues/50
=> Make table of contents by default

ubuntudesign/documentation_builder/resources/template.html
- Edited template so that if certain site metadata is passed through (`site_footer_text` and `site_footer_links`) you can customise the footer.
- Removed sorted list markup that was leftover from stealing the code from Vanilla docs
- Pull code
- Copy `ubuntudesign/documentation_builder/resources/template.html` over to `docs/template.html`
- `./run` and check that the footer looks the same as before (default canonical one)
- Now open `docs/metadata.yaml` and paste in the following code:
``` yaml
site_footer_text: 'Custom footer text'
site_footer_links:
- title: 'Link 1'
location: /link1
- title: 'Link 2'
location: /link2
```
- `./run` again and check that the footer now has a different footer
=> Allow custom footer text/links and remove leftover Vanilla markup

docs/en/homepage-examples/juju-example.md, docs/en/metadata.yaml
- Added Juju homepage example to documentation-builder docs
- Pull code
- Open `docs/metadata.yaml` and replace contents with:
``` yaml
site_title: Juju documentation
site_logo_url: https://assets.ubuntu.com/v1/9afc1e35-juju_white-orange_hex.svg
site_favicon: https://assets.ubuntu.com/v1/751b08fb-favicon.ico
site_remove_navigation_title: true
site_navigation:
- title: Store
location: https://jujucharms.com/store
- title: How it works
location: https://jujucharms.com/how-it-works
- title: JAAS
location: https://jujucharms.com/jaas
- title: Experts
location: https://jujucharms.com/experts
- title: Community
location: https://jujucharms.com/community
- title: Docs
location: /
- title: Try the beta
location: https://jujucharms.com/new/?dd=cs:bundle/canonical-kubernetes
site_navigation_colors: …
```
=> Add Juju homepage example

docs/en/homepage-examples/maas-example.md, docs/en/metadata.yaml
- Added MAAS homepage example to documentation-builder docs
- Pull code
- Open `docs/metadata.yaml` and replace contents with:
``` yaml
site_title: MAAS documentation
site_logo_url: 'https://assets.ubuntu.com/v1/4fac1d52-MAAS-Logo.svg'
site_favicon: 'https://assets.ubuntu.com/v1/5922a009-maas-favicon-32px.png'
site_remove_navigation_title: true
site_navigation:
- title: Install
location: https://maas.io/install
- title: Architecture
location: https://maas.io/how-it-works
- title: Tour
location: https://maas.io/tour
- title: Docs
location: /
selected: true
- title: Contact us
location: https://maas.io/contact-us
site_navigation_colors:
active: '#e95420'
background: '#000'
border: '#666'
hover: '#e95420'
text: '#fff'
site_footer_links:
- title: 'Legal information'
location: …
```
=> Add MAAS homepage example

docs/en/homepage-examples/conjure-up-example.md, docs/en/metadata.yaml
- Added conjure-up homepage example to documentation-builder docs
- Pull code
- Open `docs/metadata.yaml` and replace contents with:
``` yaml
site_title: Conjure-up documentation
site_logo_url: https://assets.ubuntu.com/v1/8c237d84-conjure-up-logo-black.svg
site_favicon: https://assets.ubuntu.com/v1/cb22ba5d-favicon-16x16.png
site_remove_navigation_title: true
site_navigation:
- title: User manual
location: /
- title: Developer manual
location: /dev-manual
site_footer_links:
- title: 'Legal information'
location: https://www.ubuntu.com/legal
- title: 'Report a bug on this site'
location: https://github.com/CanonicalLtd/maas-docs/issues/new
```
- Run `./run`
- Go to http://0.0.0.0:8000/en/homepage-examples/conjure-up-example
- Check that it matches the …
=> Add conjure up homepage example

tests/test_operations.py, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/operations.py, ubuntudesign/documentation_builder/resources/template.html
Fixes #96 
Add canonical url to the template when the url is provided by the flask app that is serving the files
- Build a documentation and make sure that the header has a canonical url
- build maas-docs
- Inspect HTML and make sure pages have a canonical url in the `<head>`
- It should also work for pages that has been removed in the latest version, the canonical address should be the latest version that the documentation has. (example: https://docs.maas.io/2.0/en/installconfig-nodes-deploy )
=> Add canonical url to template

tests/test_operations.py, ubuntudesign/documentation_builder/builder.py, ubuntudesign/documentation_builder/operations.py, ubuntudesign/documentation_builder/resources/template.html
Add `base_canonical` that can be passed to the templates
On maas docs copy template from resources
add line: `<link rel="canonical" href="https://docs.maas.io/{{ base_canonical }}" />` in the header
run: 
```
documentation-builder --base-directory . --output-path templates  --template-path template.html --output-media-path 'static/media' --media-url '/static/media' --tag-manager-code 'GTM-K92JCQ' --search-domain 'docs.maas.io' --search-url 'https://docs.ubuntu.com/search' --search-placeholder 'Search MAAS docs' --no-link-extensions --build-version-branches --site-root https://maas.io/
```
Make sure canonical url is right.
=> Add base canonical passed to the templates

CHANGES.txt, setup.py, ubuntudesign/documentation_builder/operations.py
Updates for Python 3.10
QA
--
In docs.ubuntu.com, in the `requirements.txt` file, replace the `ubuntudesign.documentation-builder` line with:
```
git+https://github.com/canonical/documentation-builder@python-3.10-updates#egg=ubuntudesign.documentation-builder
```
Now run `dotrun clean` and then `dotrun build`. Check the build succeeds.
Then push up that code, temporarily, to your branch and check the CI succeeds.
Then we can merge this, at which point you need to replace the line above with `ubuntudesign.documentation-builder==1.7.0`
=> v1.7.0: Updates for Python 3.10
